version: '3'

services:

  backend:
    image: backend
    ports:
      - 8000:8000

  frontend:
    image: frontend
    ports:
      - 5000:5000

  proxy:
    image: nginx
    volumes:
      - ./nginx_conf.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
